services:
- type: web
  name: meili
  env: docker
  repo: https://github.com/Amrit0991/meilisearch-docker-render.git
  plan: standard
  healthCheckPath: /
  envVars:
  - key: MEILI_HTTP_ADDR
    value: 0.0.0.0:80
  - key: MEILI_MASTER_KEY
    generateValue: true
